version: '3.8'

services:
  api:
    build: .
    tty: true
    ports:
      - 8080:80
    networks:
      - api
    volumes:
      - ./src:/var/www/app
      - /var/www/app/storage
      - /var/www/app/vendor

networks:
  api:
    driver: bridge